---
- hosts: all
  vars:
    PROJECT_HOME: "/vagrant"
  tasks:
    - name: upgrade OS packages
      sudo: yes
      apt: update-cache=yes upgrade=yes
    - name: install OS packages
      sudo: yes
      apt: pkg={{ item }} state=present
      with_items:
       - git-core
       - python-pip
    - name: install Python packages
      sudo: yes
      pip: requirements={{ PROJECT_HOME }}/requirements.txt
      tags: debug
    - name: create maildir folder
      sudo: yes
      file: path=/opt/cloudfleet/maildir/ state=directory owner=vagrant
